### ISSUE TITLE
Anyone else facing issue when running npm install this on windows OS ?

### ISSUE THREAD

**Issue by hakhan88** [academind/node-restful-api-tutorial#23]

**Comment by hakhan88** [comment]
the issue seemed to be with bcrypt, any alternatives to that dependency ?

**Comment by TarikAkyuz** [comment]
> the issue seemed to be with bcrypt, any alternatives to that dependency ?

You can use `bcryptjs` as an alternative to `bcrypt`

**Comment by hakhan88** [comment]
hmm thanks @TarikAkyuz , as an alternative i used WSL by installing ubuntu in my windows machine and that worked as well. Thanks for the help though, will close this issue
